parameters:
#    application_default.example.class: Application\DefaultBundle\Example

services:
#    application_default.example:
#        class: %application_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
